### ISSUE TITLE
Compilation errors:

### ISSUE THREAD

**Issue by erophey7** [adithya2306/android_kernel_xiaomi_lahaina#3]
```
../techpack/dataipa/drivers/platform/msm/ipa/ipa_v3/rmnet_ipa.c:512:41: error: implicit conversion from enumeration type 'enum ipa_ip_type_enum_v01' to different enumeration type 'enum ipa_ip_type' [-Werror,-Wenum-conversion]
        q6_ul_flt_rule_ptr->ip = flt_spec_ptr->ip_type;
                               ~ ~~~~~~~~~~~~~~^~~~~~~
../techpack/dataipa/drivers/platform/msm/ipa/ipa_v3/rmnet_ipa.c:513:45: error: implicit conversion from enumeration type 'enum ipa_filter_action_enum_v01' to different enumeration type 'enum ipa_flt_action' [-Werror,-Wenum-conversion]
        q6_ul_flt_rule_ptr->action = flt_spec_ptr->filter_action;
                                   ~ ~~~~~~~~~~~~~~^~~~~~~~~~~~~
2 errors generated.
make[5]: *** [../scripts/Makefile.build:288: techpack/dataipa/drivers/platform/msm/ipa/ipa_v3/rmnet_ipa.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [../scripts/Makefile.build:558: techpack/dataipa/drivers/platform/msm/ipa] Error 2
make[3]: *** [../scripts/Makefile.build:558: techpack/dataipa/drivers/platform/msm] Error 2
make[2]: *** [../scripts/Makefile.build:558: techpack/dataipa] Error 2
make[2]: *** Waiting for unfinished jobs....
../net/ipv4/tcp_timer.c:202:27: error: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Werror,-Wsingle-bit-bitfield-constant-conversion]
                icsk->icsk_mtup.enabled = 1;
                                        ^ ~
1 error generated.
make[3]: *** [../scripts/Makefile.build:288: net/ipv4/tcp_timer.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [../scripts/Makefile.build:558: net/ipv4] Error 2
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [/home/erophey7/eblya/android_kernel_xiaomi_lahaina/Makefile:1865: techpack] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [/home/erophey7/eblya/android_kernel_xiaomi_lahaina/Makefile:1865: net] Error 2
../drivers/usb/misc/usbdtp.c:730:21: error: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Werror,-Wsingle-bit-bitfield-constant-conversion]
                drv->disconnected = 1;
                                  ^ ~
../drivers/usb/misc/usbdtp.c:762:20: error: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Werror,-Wsingle-bit-bitfield-constant-conversion]
        drv->disconnected = 1;
                          ^ ~
2 errors generated.
make[4]: *** [../scripts/Makefile.build:288: drivers/usb/misc/usbdtp.o] Error 1
make[3]: *** [../scripts/Makefile.build:558: drivers/usb/misc] Error 2
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [../scripts/Makefile.build:558: drivers/usb] Error 2
make[2]: *** Waiting for unfinished jobs....
../drivers/staging/qcacld-3.0/core/mac/src/sys/legacy/src/utils/src/parser_api.c:6163:14: error: argument 'mdie' of type 'uint8_t[3]' (aka 'unsigned char[3]') with mismatched bound [-Werror,-Warray-parameter]
                   uint8_t mdie[SIR_MDIE_SIZE])
                           ^
../drivers/staging/qcacld-3.0/core/mac/src/include/parser_api.h:1055:14: note: previously declared as 'uint8_t[]' (aka 'unsigned char[]') here
                   uint8_t mdie[]);
                           ^
1 error generated.
make[4]: *** [../scripts/Makefile.build:288: drivers/staging/qcacld-3.0/core/mac/src/sys/legacy/src/utils/src/parser_api.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [../scripts/Makefile.build:558: drivers/staging/qcacld-3.0] Error 2
make[2]: *** [../scripts/Makefile.build:558: drivers/staging] Error 2
make[1]: *** [/home/erophey7/eblya/android_kernel_xiaomi_lahaina/Makefile:1865: drivers] Error 2
make: *** [Makefile:183: sub-make] Error 2

```
Full log: https://pastebin.com/V7s3Ngth
GCC 32bit: https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+/refs/tags/android-13.0.0_r0.122
GCC 64bit: https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+/refs/heads/android-arm64-deadpool-4.9-android13-tv
Clang: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/heads/android-arm64-deadpool-4.9-android13-tv

**Comment by adithya2306** [comment]
that seems like a newer clang than what i am using, feel free to upload pull request.

**Comment by erophey7** [comment]
Thank you for your answer, but I have already fixed this error, but I have another problem.  I wanted to build an external module for the rtl8811au adapter, but I have a problem:
 
```
erophey7@compudahter-kubuntu:~/eblya/8821au-20210708$ make -C $HOME/eblya/android_kernel_xiaomi_lahaina/out M=$PWD ARCH=arm64 CC=clang CLANG_TRIPLE=aarch64-linux-gnu- LLVM=1 LLVM_IAS=1 CROSS_COMPILE  =$TC_DIR/bin/llvm- make: 
Entering directory '/home/erophey7/eblya/android_kernel_xiaomi_lahaina/out'
Building modules, stage 2. 
MODPOST 0 modules make: 
Leaving directory '/home/erophey7/eblya/android_kernel_xiaomi_lahaina/out'
```

 driver source: https://github.com/morrownr/8821au-20210708
 instructions for which I tried to compile: https://www.kernel.org/doc/Documentation/kbuild/modules.txt

**Comment by Manan-Santoki** [comment]
> ```
> ../techpack/dataipa/drivers/platform/msm/ipa/ipa_v3/rmnet_ipa.c:512:41: error: implicit conversion from enumeration type 'enum ipa_ip_type_enum_v01' to different enumeration type 'enum ipa_ip_type' [-Werror,-Wenum-conversion]
>         q6_ul_flt_rule_ptr->ip = flt_spec_ptr->ip_type;
>                                ~ ~~~~~~~~~~~~~~^~~~~~~
> ../techpack/dataipa/drivers/platform/msm/ipa/ipa_v3/rmnet_ipa.c:513:45: error: implicit conversion from enumeration type 'enum ipa_filter_action_enum_v01' to different enumeration type 'enum ipa_flt_action' [-Werror,-Wenum-conversion]
>         q6_ul_flt_rule_ptr->action = flt_spec_ptr->filter_action;
>                                    ~ ~~~~~~~~~~~~~~^~~~~~~~~~~~~
> 2 errors generated.
> make[5]: *** [../scripts/Makefile.build:288: techpack/dataipa/drivers/platform/msm/ipa/ipa_v3/rmnet_ipa.o] Error 1
> make[5]: *** Waiting for unfinished jobs....
> make[4]: *** [../scripts/Makefile.build:558: techpack/dataipa/drivers/platform/msm/ipa] Error 2
> make[3]: *** [../scripts/Makefile.build:558: techpack/dataipa/drivers/platform/msm] Error 2
> make[2]: *** [../scripts/Makefile.build:558: techpack/dataipa] Error 2
> make[2]: *** Waiting for unfinished jobs....
> ../net/ipv4/tcp_timer.c:202:27: error: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Werror,-Wsingle-bit-bitfield-constant-conversion]
>                 icsk->icsk_mtup.enabled = 1;
>                                         ^ ~
> 1 error generated.
> make[3]: *** [../scripts/Makefile.build:288: net/ipv4/tcp_timer.o] Error 1
> make[3]: *** Waiting for unfinished jobs....
> make[2]: *** [../scripts/Makefile.build:558: net/ipv4] Error 2
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [/home/erophey7/eblya/android_kernel_xiaomi_lahaina/Makefile:1865: techpack] Error 2
> make[1]: *** Waiting for unfinished jobs....
> make[1]: *** [/home/erophey7/eblya/android_kernel_xiaomi_lahaina/Makefile:1865: net] Error 2
> ../drivers/usb/misc/usbdtp.c:730:21: error: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Werror,-Wsingle-bit-bitfield-constant-conversion]
>                 drv->disconnected = 1;
>                                   ^ ~
> ../drivers/usb/misc/usbdtp.c:762:20: error: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Werror,-Wsingle-bit-bitfield-constant-conversion]
>         drv->disconnected = 1;
>                           ^ ~
> 2 errors generated.
> make[4]: *** [../scripts/Makefile.build:288: drivers/usb/misc/usbdtp.o] Error 1
> make[3]: *** [../scripts/Makefile.build:558: drivers/usb/misc] Error 2
> make[3]: *** Waiting for unfinished jobs....
> make[2]: *** [../scripts/Makefile.build:558: drivers/usb] Error 2
> make[2]: *** Waiting for unfinished jobs....
> ../drivers/staging/qcacld-3.0/core/mac/src/sys/legacy/src/utils/src/parser_api.c:6163:14: error: argument 'mdie' of type 'uint8_t[3]' (aka 'unsigned char[3]') with mismatched bound [-Werror,-Warray-parameter]
>                    uint8_t mdie[SIR_MDIE_SIZE])
>                            ^
> ../drivers/staging/qcacld-3.0/core/mac/src/include/parser_api.h:1055:14: note: previously declared as 'uint8_t[]' (aka 'unsigned char[]') here
>                    uint8_t mdie[]);
>                            ^
> 1 error generated.
> make[4]: *** [../scripts/Makefile.build:288: drivers/staging/qcacld-3.0/core/mac/src/sys/legacy/src/utils/src/parser_api.o] Error 1
> make[4]: *** Waiting for unfinished jobs....
> make[3]: *** [../scripts/Makefile.build:558: drivers/staging/qcacld-3.0] Error 2
> make[2]: *** [../scripts/Makefile.build:558: drivers/staging] Error 2
> make[1]: *** [/home/erophey7/eblya/android_kernel_xiaomi_lahaina/Makefile:1865: drivers] Error 2
> make: *** [Makefile:183: sub-make] Error 2
> ```
> 
> Full log: https://pastebin.com/V7s3Ngth GCC 32bit: https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+/refs/tags/android-13.0.0_r0.122 GCC 64bit: https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+/refs/heads/android-arm64-deadpool-4.9-android13-tv Clang: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/heads/android-arm64-deadpool-4.9-android13-tv

can you please share the fixes ?

> ```
> ../techpack/dataipa/drivers/platform/msm/ipa/ipa_v3/rmnet_ipa.c:512:41: error: implicit conversion from enumeration type 'enum ipa_ip_type_enum_v01' to different enumeration type 'enum ipa_ip_type' [-Werror,-Wenum-conversion]
>         q6_ul_flt_rule_ptr->ip = flt_spec_ptr->ip_type;
>                                ~ ~~~~~~~~~~~~~~^~~~~~~
> ../techpack/dataipa/drivers/platform/msm/ipa/ipa_v3/rmnet_ipa.c:513:45: error: implicit conversion from enumeration type 'enum ipa_filter_action_enum_v01' to different enumeration type 'enum ipa_flt_action' [-Werror,-Wenum-conversion]
>         q6_ul_flt_rule_ptr->action = flt_spec_ptr->filter_action;
>                                    ~ ~~~~~~~~~~~~~~^~~~~~~~~~~~~
> 2 errors generated.
> make[5]: *** [../scripts/Makefile.build:288: techpack/dataipa/drivers/platform/msm/ipa/ipa_v3/rmnet_ipa.o] Error 1
> make[5]: *** Waiting for unfinished jobs....
> make[4]: *** [../scripts/Makefile.build:558: techpack/dataipa/drivers/platform/msm/ipa] Error 2
> make[3]: *** [../scripts/Makefile.build:558: techpack/dataipa/drivers/platform/msm] Error 2
> make[2]: *** [../scripts/Makefile.build:558: techpack/dataipa] Error 2
> make[2]: *** Waiting for unfinished jobs....
> ../net/ipv4/tcp_timer.c:202:27: error: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Werror,-Wsingle-bit-bitfield-constant-conversion]
>                 icsk->icsk_mtup.enabled = 1;
>                                         ^ ~
> 1 error generated.
> make[3]: *** [../scripts/Makefile.build:288: net/ipv4/tcp_timer.o] Error 1
> make[3]: *** Waiting for unfinished jobs....
> make[2]: *** [../scripts/Makefile.build:558: net/ipv4] Error 2
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [/home/erophey7/eblya/android_kernel_xiaomi_lahaina/Makefile:1865: techpack] Error 2
> make[1]: *** Waiting for unfinished jobs....
> make[1]: *** [/home/erophey7/eblya/android_kernel_xiaomi_lahaina/Makefile:1865: net] Error 2
> ../drivers/usb/misc/usbdtp.c:730:21: error: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Werror,-Wsingle-bit-bitfield-constant-conversion]
>                 drv->disconnected = 1;
>                                   ^ ~
> ../drivers/usb/misc/usbdtp.c:762:20: error: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Werror,-Wsingle-bit-bitfield-constant-conversion]
>         drv->disconnected = 1;
>                           ^ ~
> 2 errors generated.
> make[4]: *** [../scripts/Makefile.build:288: drivers/usb/misc/usbdtp.o] Error 1
> make[3]: *** [../scripts/Makefile.build:558: drivers/usb/misc] Error 2
> make[3]: *** Waiting for unfinished jobs....
> make[2]: *** [../scripts/Makefile.build:558: drivers/usb] Error 2
> make[2]: *** Waiting for unfinished jobs....
> ../drivers/staging/qcacld-3.0/core/mac/src/sys/legacy/src/utils/src/parser_api.c:6163:14: error: argument 'mdie' of type 'uint8_t[3]' (aka 'unsigned char[3]') with mismatched bound [-Werror,-Warray-parameter]
>                    uint8_t mdie[SIR_MDIE_SIZE])
>                            ^
> ../drivers/staging/qcacld-3.0/core/mac/src/include/parser_api.h:1055:14: note: previously declared as 'uint8_t[]' (aka 'unsigned char[]') here
>                    uint8_t mdie[]);
>                            ^
> 1 error generated.
> make[4]: *** [../scripts/Makefile.build:288: drivers/staging/qcacld-3.0/core/mac/src/sys/legacy/src/utils/src/parser_api.o] Error 1
> make[4]: *** Waiting for unfinished jobs....
> make[3]: *** [../scripts/Makefile.build:558: drivers/staging/qcacld-3.0] Error 2
> make[2]: *** [../scripts/Makefile.build:558: drivers/staging] Error 2
> make[1]: *** [/home/erophey7/eblya/android_kernel_xiaomi_lahaina/Makefile:1865: drivers] Error 2
> make: *** [Makefile:183: sub-make] Error 2
> ```
> 
> Full log: https://pastebin.com/V7s3Ngth GCC 32bit: https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+/refs/tags/android-13.0.0_r0.122 GCC 64bit: https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+/refs/heads/android-arm64-deadpool-4.9-android13-tv Clang: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/heads/android-arm64-deadpool-4.9-android13-tv

Hey! can you please share the fixes to fix this compilation error ?

**Comment by Manan-Santoki** [comment]
> ```
> ../techpack/dataipa/drivers/platform/msm/ipa/ipa_v3/rmnet_ipa.c:512:41: error: implicit conversion from enumeration type 'enum ipa_ip_type_enum_v01' to different enumeration type 'enum ipa_ip_type' [-Werror,-Wenum-conversion]
>         q6_ul_flt_rule_ptr->ip = flt_spec_ptr->ip_type;
>                                ~ ~~~~~~~~~~~~~~^~~~~~~
> ../techpack/dataipa/drivers/platform/msm/ipa/ipa_v3/rmnet_ipa.c:513:45: error: implicit conversion from enumeration type 'enum ipa_filter_action_enum_v01' to different enumeration type 'enum ipa_flt_action' [-Werror,-Wenum-conversion]
>         q6_ul_flt_rule_ptr->action = flt_spec_ptr->filter_action;
>                                    ~ ~~~~~~~~~~~~~~^~~~~~~~~~~~~
> 2 errors generated.
> make[5]: *** [../scripts/Makefile.build:288: techpack/dataipa/drivers/platform/msm/ipa/ipa_v3/rmnet_ipa.o] Error 1
> make[5]: *** Waiting for unfinished jobs....
> make[4]: *** [../scripts/Makefile.build:558: techpack/dataipa/drivers/platform/msm/ipa] Error 2
> make[3]: *** [../scripts/Makefile.build:558: techpack/dataipa/drivers/platform/msm] Error 2
> make[2]: *** [../scripts/Makefile.build:558: techpack/dataipa] Error 2
> make[2]: *** Waiting for unfinished jobs....
> ../net/ipv4/tcp_timer.c:202:27: error: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Werror,-Wsingle-bit-bitfield-constant-conversion]
>                 icsk->icsk_mtup.enabled = 1;
>                                         ^ ~
> 1 error generated.
> make[3]: *** [../scripts/Makefile.build:288: net/ipv4/tcp_timer.o] Error 1
> make[3]: *** Waiting for unfinished jobs....
> make[2]: *** [../scripts/Makefile.build:558: net/ipv4] Error 2
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [/home/erophey7/eblya/android_kernel_xiaomi_lahaina/Makefile:1865: techpack] Error 2
> make[1]: *** Waiting for unfinished jobs....
> make[1]: *** [/home/erophey7/eblya/android_kernel_xiaomi_lahaina/Makefile:1865: net] Error 2
> ../drivers/usb/misc/usbdtp.c:730:21: error: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Werror,-Wsingle-bit-bitfield-constant-conversion]
>                 drv->disconnected = 1;
>                                   ^ ~
> ../drivers/usb/misc/usbdtp.c:762:20: error: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Werror,-Wsingle-bit-bitfield-constant-conversion]
>         drv->disconnected = 1;
>                           ^ ~
> 2 errors generated.
> make[4]: *** [../scripts/Makefile.build:288: drivers/usb/misc/usbdtp.o] Error 1
> make[3]: *** [../scripts/Makefile.build:558: drivers/usb/misc] Error 2
> make[3]: *** Waiting for unfinished jobs....
> make[2]: *** [../scripts/Makefile.build:558: drivers/usb] Error 2
> make[2]: *** Waiting for unfinished jobs....
> ../drivers/staging/qcacld-3.0/core/mac/src/sys/legacy/src/utils/src/parser_api.c:6163:14: error: argument 'mdie' of type 'uint8_t[3]' (aka 'unsigned char[3]') with mismatched bound [-Werror,-Warray-parameter]
>                    uint8_t mdie[SIR_MDIE_SIZE])
>                            ^
> ../drivers/staging/qcacld-3.0/core/mac/src/include/parser_api.h:1055:14: note: previously declared as 'uint8_t[]' (aka 'unsigned char[]') here
>                    uint8_t mdie[]);
>                            ^
> 1 error generated.
> make[4]: *** [../scripts/Makefile.build:288: drivers/staging/qcacld-3.0/core/mac/src/sys/legacy/src/utils/src/parser_api.o] Error 1
> make[4]: *** Waiting for unfinished jobs....
> make[3]: *** [../scripts/Makefile.build:558: drivers/staging/qcacld-3.0] Error 2
> make[2]: *** [../scripts/Makefile.build:558: drivers/staging] Error 2
> make[1]: *** [/home/erophey7/eblya/android_kernel_xiaomi_lahaina/Makefile:1865: drivers] Error 2
> make: *** [Makefile:183: sub-make] Error 2
> ```
> 
> Full log: https://pastebin.com/V7s3Ngth GCC 32bit: https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+/refs/tags/android-13.0.0_r0.122 GCC 64bit: https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+/refs/heads/android-arm64-deadpool-4.9-android13-tv Clang: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/heads/android-arm64-deadpool-4.9-android13-tv

Hey! can you please share the fixes for the compilation error ?
